spring:
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/fundtransfer_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET:AWOum5UmQdECMaapOD/HiEZfCMbKZG0EYQ0Vd7rwUIS8JWbrdCmBRbvaRKSPziPLAYv/6w3eN/7opl4xw89Iyw==}
  #3600000 = 60mins
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
